# Generated by Django 2.0.5 on 2018-06-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyFeedapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='desciption',
            new_name='description',
        ),
    ]
