# Generated by Django 2.0.5 on 2018-07-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFeedapp', '0002_auto_20180629_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publishedAt',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='urlToImage',
            field=models.URLField(null=True),
        ),
    ]
